03/28/2024 04:12:15 - WARNING - __main__ -   Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
03/28/2024 04:12:15 - INFO - __main__ -   Training/evaluation parameters CoCondenserPreTrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
cache_chunk_size=-1,
data_seed=None,
dataloader_drop_last=True,
dataloader_num_workers=16,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=5000.0,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=co_condenser_pretrain/runs/Mar28_04-12-15_afa8263c8862,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1.0,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=8.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
output_dir=co_condenser_pretrain,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=False,
report_to=['wandb'],
resume_from_checkpoint=None,
run_name=co_condenser_pretrain,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=20000,
save_strategy=steps,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)
[INFO|configuration_utils.py:724] 2024-03-28 04:12:15,615 >> loading configuration file /root/condenser_pretrain/checkpoint-260000/config.json
[INFO|configuration_utils.py:789] 2024-03-28 04:12:15,616 >> Model config BertConfig {
  "_name_or_path": "/root/condenser_pretrain/checkpoint-260000/",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.39.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 61790
}

[INFO|tokenization_utils_base.py:2082] 2024-03-28 04:12:15,617 >> loading file vocab.txt
[INFO|tokenization_utils_base.py:2082] 2024-03-28 04:12:15,617 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2082] 2024-03-28 04:12:15,617 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2082] 2024-03-28 04:12:15,617 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2082] 2024-03-28 04:12:15,617 >> loading file tokenizer.json
[INFO|modeling_utils.py:3280] 2024-03-28 04:12:15,681 >> loading weights file /root/condenser_pretrain/checkpoint-260000/model.safetensors
[INFO|configuration_utils.py:928] 2024-03-28 04:12:15,713 >> Generate config GenerationConfig {
  "pad_token_id": 0
}

[INFO|modeling_utils.py:4024] 2024-03-28 04:12:18,150 >> All model checkpoint weights were used when initializing BertForMaskedLM.

[INFO|modeling_utils.py:4032] 2024-03-28 04:12:18,150 >> All the weights of BertForMaskedLM were initialized from the model checkpoint at /root/condenser_pretrain/checkpoint-260000/.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertForMaskedLM for predictions without further training.
[INFO|configuration_utils.py:881] 2024-03-28 04:12:18,169 >> loading configuration file /root/condenser_pretrain/checkpoint-260000/generation_config.json
[INFO|configuration_utils.py:928] 2024-03-28 04:12:18,169 >> Generate config GenerationConfig {
  "pad_token_id": 0
}

03/28/2024 04:12:18 - INFO - modeling -   loading extra weights from local files
-------------------------------------------
loading json . . .
en_index.json load complete! 297.04139828681946 seconds took.
ko_index.json load complete! 505.71901774406433 seconds took.
03/28/2024 04:25:41 - INFO - trainer -   Initializing Gradient Cache Trainer
/root/con_venv/lib/python3.9/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
[INFO|trainer.py:1969] 2024-03-28 04:28:36,878 >> ***** Running training *****
[INFO|trainer.py:1970] 2024-03-28 04:28:36,878 >>   Num examples = 31,122,906
[INFO|trainer.py:1971] 2024-03-28 04:28:36,878 >>   Num Epochs = 8
[INFO|trainer.py:1972] 2024-03-28 04:28:36,878 >>   Instantaneous batch size per device = 8
[INFO|trainer.py:1975] 2024-03-28 04:28:36,878 >>   Total train batch size (w. parallel, distributed & accumulation) = 8
[INFO|trainer.py:1976] 2024-03-28 04:28:36,878 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1977] 2024-03-28 04:28:36,878 >>   Total optimization steps = 31,122,904
[INFO|trainer.py:1978] 2024-03-28 04:28:36,879 >>   Number of trainable parameters = 147,735,134
[INFO|integration_utils.py:723] 2024-03-28 04:28:36,880 >> Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
wandb: Currently logged in as: 3jp4rk. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.5
wandb: Run data is saved locally in /root/wandb/run-20240328_042842-iaatz3b8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run solar-tree-8
wandb: ‚≠êÔ∏è View project at https://wandb.ai/3jp4rk/coCondenser-bert-pretrain
wandb: üöÄ View run at https://wandb.ai/3jp4rk/coCondenser-bert-pretrain/runs/iaatz3b8/workspace
  0%|          | 0/31122904 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/Condenser/run_co_pre_training.py", line 213, in <module>
    main()
  File "/root/Condenser/run_co_pre_training.py", line 203, in main
    trainer.train()
  File "/root/con_venv/lib/python3.9/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/root/con_venv/lib/python3.9/site-packages/transformers/trainer.py", line 2085, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/root/con_venv/lib/python3.9/site-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/con_venv/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/con_venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/marco_dataset.py", line 372, in __getitem__
    return self.get_data(self.train2full(idx))
  File "/root/marco_dataset.py", line 410, in get_data
    selected = get_doc_passage(self.data_idx, ds, idx)
  File "/root/marco_dataset.py", line 269, in get_doc_passage
    passage_idx = random.sample(len(doc_passages), 1)
  File "/usr/lib/python3.9/random.py", line 434, in sample
    raise TypeError("Population must be a sequence.  For dicts or sets, use sorted(d).")
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

wandb: - 0.028 MB of 0.037 MB uploadedwandb: \ 0.037 MB of 0.037 MB uploadedwandb: üöÄ View run solar-tree-8 at: https://wandb.ai/3jp4rk/coCondenser-bert-pretrain/runs/iaatz3b8/workspace
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240328_042842-iaatz3b8/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread IntMsgThr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self.run()
      File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
        self._target(*self._args, **self._kwargs)self._loop_check_status(

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
        local_handle = request()self._loop_check_status(

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 836, in deliver_network_status
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
        return self._deliver_network_status(status)local_handle = request()

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 510, in _deliver_network_status
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 844, in deliver_internal_messages
    return self._deliver_record(record)    
return self._deliver_internal_messages(internal_message)  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 459, in _deliver_record

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 516, in _deliver_internal_messages
    handle = mailbox._deliver_record(record, interface=self)
      File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
return self._deliver_record(record)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 459, in _deliver_record
    interface._publish(record)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    handle = mailbox._deliver_record(record, interface=self)
      File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
self._sock_client.send_record_publish(record)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    interface._publish(record)
      File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
self.send_server_request(server_req)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._sock_client.send_record_publish(record)
      File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
self._send_message(msg)
  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self.send_server_request(server_req)    
self._sendall_with_error_handle(header + data)  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    self._send_message(msg)
      File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
sent = self._sock.send(data)
BrokenPipeError:     [Errno 32] Broken pipeself._sendall_with_error_handle(header + data)

  File "/root/con_venv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
[2024-03-28 04:41:29,446] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 34830) of binary: /root/con_venv/bin/python3.9
Traceback (most recent call last):
  File "/root/con_venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/con_venv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/con_venv/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/con_venv/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/con_venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/con_venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_co_pre_training.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-28_04:41:29
  host      : afa8263c8862
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 34830)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
